// GENERATED by scripts/pxl/build-pxl-media.mjs — do not edit by hand.
// Run `npm run pxl` to regenerate.
//
// Duna PXL design renders. These are the studio's own images, not photography:
// the boat is new and has not been shot. Treat them as the reference for what
// the real-time model has to look like, and as the fallback the WebGL scene
// falls back *to*.

export interface PxlMediaAsset {
  readonly id: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly alt: string;
  readonly blurDataURL: string;
  /** The delivered file this was derived from. */
  readonly source: string;
}

export const PXL_MEDIA = {
  "pxl-hero-side": {
    id: "pxl-hero-side",
    src: "/media/pxl/pxl-hero-side.webp",
    width: 2000,
    height: 855,
    alt: "The Duna PXL in profile, bow to the right, in the design studio's own render.",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAwCdASoUAAkAPwlusE+rpiSiMAgBcCEJaQAAW/ACNVSqAAD+7eGEttd5AsYoEqvuqiYou/ViQi32UNRvoHGbLiL/7nnnI9feOfd8vZ2zXMTsAAA=",
    source: "assets/source/pxl/pxl-side-20240719.jpg",
  },
  "pxl-views": {
    id: "pxl-views",
    src: "/media/pxl/pxl-views.webp",
    width: 2000,
    height: 1314,
    alt: "Three studies of the Duna PXL: profile, cockpit from above, and stern quarter.",
    blurDataURL: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACwAwCdASoUAA0APwlur0+rpiQiMAgBcCEJaQAAUgVQVv4QlPXEAAD+7dWqHW2Xo/IKqfoM5prcbI3fOoKDylAr2Iu+8pjul+X8Yv5YohQU9r9QcxQfE0BAHPKEctnbzolSAAAA",
    source: "assets/source/pxl/pxl-views-20240815c.jpg",
  },
  "pxl-water-white": {
    id: "pxl-water-white",
    src: "/media/pxl/pxl-water-white.webp",
    width: 1800,
    height: 686,
    alt: "The Duna PXL on open water with a white hull.",
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwBACdASoUAAgAPwlwsFArpiSisAgBcCEJYgCdMoGv/gPQ2lZMUvs3S5AA/lvwSJOtjI4POXMrs0YTST2x7rODE/l33+s6P7diUjCxr5wMSEWSnusMfUHv+xsvrGse+gAAAA==",
    source: "assets/source/pxl/pxl-colours-01.jpg",
  },
  "pxl-water-sage": {
    id: "pxl-water-sage",
    src: "/media/pxl/pxl-water-sage.webp",
    width: 1800,
    height: 686,
    alt: "The Duna PXL on open water with a sage-green hull.",
    blurDataURL: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoUAAgAPwlurk+rpiQiMAgBcCEJYgCdMoGv/gPNTKn4ej2AAP3jlKpuGxYsqdDZltp19JPQGlUj8pRnxuvor16a9EokkslPXgtzZMcDoYUYAAAA",
    source: "assets/source/pxl/pxl-colours-01.jpg",
  },
  "pxl-water-black": {
    id: "pxl-water-black",
    src: "/media/pxl/pxl-water-black.webp",
    width: 1800,
    height: 686,
    alt: "The Duna PXL on open water with a black hull.",
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoUAAgAPwlwsFArpqSisAgBcCEJYgCdMoGv/gPNdr8Tc4acAAD+W/Bclhoe6ZSYPL0gZQMSm0qkflK0FOLZRD687QaRxOUfuibrj+qt9tVTAh6tAAA=",
    source: "assets/source/pxl/pxl-colours-02.jpg",
  },
  "pxl-water-warm-grey": {
    id: "pxl-water-warm-grey",
    src: "/media/pxl/pxl-water-warm-grey.webp",
    width: 1800,
    height: 686,
    alt: "The Duna PXL on open water with a warm grey hull.",
    blurDataURL: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoUAAgAPwlyr1ArpyQisAgBcCEJYgCdMoGv/gPQlvbdyoTk5+wA/lvwMqpcdJdU3v7B05IzWEzjgBpVI/KRjIJ+6YkVE0NBdzMNXCiTCoPf9jZfWNY99AAA",
    source: "assets/source/pxl/pxl-colours-03.jpg",
  },
  "pxl-water-gold": {
    id: "pxl-water-gold",
    src: "/media/pxl/pxl-water-gold.webp",
    width: 1800,
    height: 686,
    alt: "The Duna PXL on open water with a gold hull.",
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQBACdASoUAAgAPwlwsVArpiSisAgBcCEJZACdMoR4LftgPQcjW8yjmZ4AAP5b8DCO/axuJ96VyMR96v19RXKOihJATp7EAPUgArc467LzlT4BaghM0uRpvs6UZz+ehOAAAA==",
    source: "assets/source/pxl/pxl-colours-04.jpg",
  },
  "pxl-water-navy": {
    id: "pxl-water-navy",
    src: "/media/pxl/pxl-water-navy.webp",
    width: 1800,
    height: 686,
    alt: "The Duna PXL on open water with a navy hull.",
    blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUAAgAPwlurk+rpiQiMAgBcCEJYgCdMoR3Ff/gPNUyP7Y/JIAA/eOVGv3rFYX+Odr5A2j+cQfEdncA8YjYq21hG6L/NM0d+xOyuH1BwGGp7sDCjAAAAA==",
    source: "assets/source/pxl/pxl-colours-04.jpg",
  },
} as const satisfies Record<string, PxlMediaAsset>;

export type PxlMediaId = keyof typeof PXL_MEDIA;
