// GENERATED by scripts/build-vessel-plate.mjs — do not edit by hand.
// Run `npm run vessel` to regenerate.

export interface VesselPlate {
  readonly id: string;
  readonly label: string;
  readonly src: string;
  readonly width: number;
  readonly height: number;
  /** Which way the photographed bow points in image space. */
  readonly facing: "left" | "right";
  /** Visible length overall of the matte, in metres. */
  readonly metres: number;
  readonly metresPerPixel: number;
  /** Distance from the waterline to the top of the matte, in metres. */
  readonly heightMetres: number;
}

export const VESSEL_PLATES = {
  "duna61-cabin-profile": {
    id: "duna61-cabin-profile",
    label: "Duna 6.1 Cabin, studio profile",
    src: "/media/vessel/duna61-cabin-profile.png",
    width: 1049,
    height: 379,
    facing: "right",
    metres: 6.72,
    metresPerPixel: 0.00640610,
    heightMetres: 2.4279,
  },
} as const satisfies Record<string, VesselPlate>;

export type VesselPlateId = keyof typeof VESSEL_PLATES;
